language: php

sudo: true

env:
  global:
    - CC_TEST_REPORTER_ID=4f8327fbe90144089ea73dc9c26471edf7a6ccd2c06ab156de73abdde6e03a61
    - COVERAGE=0

matrix:
  include:
    - php: 7.2
      env: LARAVEL='6.0.*'
    - php: 7.3
      env: COVERAGE=1 LARAVEL='6.0.*'
    - php: 7.4snapshot
      env: LARAVEL='6.0.*'
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

services:
  - sqlite

before_script:
  - composer config discard-changes true
  - if [[ $COVERAGE = '1' ]]; then ./bin/codeclimate setup; fi
  - npm install
  - npm run dev

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/support:${LARAVEL}" --no-interaction --no-update
  - composer show illuminate/support

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - if [[ $COVERAGE = 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $COVERAGE = 0 ]]; then vendor/bin/phpunit --no-coverage; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then ./bin/codeclimate report $TRAVIS_TEST_RESULT; fi