language: php

sudo: true

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.2
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

services:
  - sqlite
  - mysql
  - postgres

before_script:
  - composer install
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'create database test;' -U postgres

script:
  # - vendor/bin/phpunit

env:
  - DB_DRIVER=sqlite
  - DB_DRIVER=mysql
  - DB_DRIVER=postgres
