language: php

sudo: true

php:
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  matrix:
    - LARAVEL_VERSION=5.8.*
  global:
    - CC_TEST_REPORTER_ID=4f8327fbe90144089ea73dc9c26471edf7a6ccd2c06ab156de73abdde6e03a61

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

services:
  - sqlite

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - travis_retry composer self-update
  - composer require "illuminate/support:${LARAVEL_VERSION}"
  - composer show laravel/framework
  - npm install
  - npm run dev

script:
  - vendor/bin/phpunit

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT